### ISSUE TITLE
May need to use json interpreter

### ISSUE THREAD

**Issue by ZynoXelek** [iScsc/PotatOnline#10]
We may need to use json interpreter instead of our custom interpreter as the complexity of our game increase and the amount of Class to save and transmit increase.
It would also be easier to save maps in a file for instance. (Or we could do it ourselves.)

**Comment by BlueNZ** [comment]
Won't there be any issues with the interpreter as there was with the `eval` function ?

**Comment by ZynoXelek** [comment]
This should not be mandatory anymore now that our custom interpretor has been improved!
